- hosts: build

  vars_prompt:
    - name: admin_user
      prompt: "service admin user"
      default: "admin"
    - name: admin_pass
      prompt: "service admin password"
      private: yes

  vars_files:
    - ./vars/users.yml
  remote_user: root

  roles:
    - { role: docker }
    - { role: devserver, group: "dev", other_groups: "docker" }
    - { role: jenkins }
    - { role: nginx }

- hosts: repo

  remote_user: root

  roles:
    - { role: docker }
    - { role: nginx }
    - { role: nexus }
