- hosts: build

  vars_files:
    - ./vars/users.yml
  remote_user: root

  roles:
    - { role: docker }
    - { role: devserver, group: "dev", other_groups: "docker" }
    - { role: jenkins }
    - { role: nginx }
