---
- name: create dev group
  group: name={{ group }} state=present

- name: make dev sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ group }}' line='%{{ group }} ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"

- name: create dev users
  user: name={{ item }} state=present shell=/bin/bash group={{ group }} groups={{ other_groups }}
  with_items: "{{ users }}"

- name: configure with github authorized keys
  authorized_key: user={{ item }} key=https://github.com/{{ item }}.keys
  with_items: "{{ users }}"