---
- name: copy docker files to server
  copy: src=./ dest={{ docker_tmp_dir }}

- name: template out jenkins security setup groovy script to server
  template: src=config/setup-security.groovy.j2 dest={{ docker_tmp_dir }}/config/setup-security.groovy

- name: build jenkins server docker image
  docker_image:
    path: "{{ docker_tmp_dir }}"
    name: gradame/jenkins
  notify:
    - cleanup temp dir

- name: run jenkins server
  docker:
    name: gradame_ci
    image: gradame/jenkins
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
      - "50000:50000"

- name: configure jenkins in nginx
  template: src=sites/build.grada.me.j2 dest=/etc/nginx/sites-available/build.grada.me owner=root group=root mode=0644

- name: create configuration symlink in nginx
  file: src=/etc/nginx/sites-available/build.grada.me dest=/etc/nginx/sites-enabled/build.grada.me state=link
  notify:
    - reload nginx
