- name: add docker apt key
  apt_key: keyserver={{ docker_keyserver }} id={{ docker_key_id }} state=present

- name: add docker apt repo
  apt_repository: repo={{ docker_apt_repo }} state=present

- name: install docker-engine
  apt: pkg=docker-engine state=present

- name: make sure docker service is started
  service: name=docker state=started