- name: add docker apt key
  apt_key: keyserver={{ docker_keyserver }} id={{ docker_key_id }} state=present

- name: add docker apt repo
  apt_repository: repo={{ docker_apt_repo }} state=present

- name: install docker-engine
  apt: pkg=docker-engine state=present

- name: create docker systemd drop-in directory
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: copy docker.config file
  copy: src=docker.config dest=/etc/systemd/system/docker.service.d/docker.conf owner=root group=root mode=0644
  notify:
  - systemctl daemon-reload
  - restart docker

- name: enable docker service
  service: name=docker state=started enabled=yes

