---
- name: set ARTIFACTORY_HOME env variable
  lineinfile: dest=/etc/environment state=present regexp='^export ARTIFACTORY_HOME' line='export ARTIFACTORY_HOME=/var/opt/jfrog/artifactory'

- name: run artifactory server
  docker:
    name: gradame_repo
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:latest
    state: started
    restart_policy: always
    ports:
      - "8081:8081"

- name: configure artifactory in nginx
  template: src=sites/repo.grada.me.j2 dest=/etc/nginx/sites-available/repo.grada.me owner=root group=root mode=0644

- name: create artifactory configuration symlink in nginx
  file: src=/etc/nginx/sites-available/repo.grada.me dest=/etc/nginx/sites-enabled/repo.grada.me state=link
  notify:
    - reload nginx
